version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    # EXPLICITAMENTE SEM HEALTHCHECK
    # healthcheck: disable
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
